commitlint.config.js, package.json
* unwelcoming for new contributors
* doesn't cover the case where the commits are adjusted/squashed at landing time on GitHub
=> chore: backoff from using commitlint

README.md, bin/format-check.sh, package-lock.json, package.json, src/cli.ts, src/init.ts, src/lint.ts, test/fixtures/kitchen/package.json, test/test-clean.ts, test/test-kitchen.ts, test/test-lint.ts
* Use `gts` as the only name going forward.
* Ability to check format.
=> breaking: rename module

.gitignore, .travis.yml, package-lock.json, package.json
Fixes: https://github.com/google/ts-style/issues/31
=> chore: setup code-coverage

src/cli.ts, src/init.ts, test/test-clean.ts, test/test-kitchen.ts, test/test-lint.ts
=> feat: run npm install after init

package-lock.json, package.json
I cannot execute `npm run clean` on Windows.
This  pull request makes npm-script to cross platform friendly.
=> cross platform friendly

package-lock.json, package.json, test/test-kitchen.ts
This release includes a fix for
https://github.com/google/ts-style/issues/128.
The draft release notes are in https://github.com/google/ts-style/releases/tag/untagged-8ad589cd37ce5d87c562
=> chore: release 0.5.4

.circleci/config.yml
Also run docker as non-root user.
=> chore: integrate NPM publish with CircleCI

package-lock.json, package.json
I don't think we should pin them.
=> chore: unpin some packages

package-lock.json, package.json, src/cli.ts, src/init.ts, src/util.ts, test/fixtures.ts, test/test-kitchen.ts, tsconfig-google.json
With the EOL of Node 4 imminent, let's rebase `next` onto `master`, and start working on 1.0 on `master`.
=> Rebase `next` onto `master`

src/cli.ts
Fixes: https://github.com/google/ts-style/issues/165
=> fix: properly specify cmdline flags to meow

package-lock.json, package.json
Release notes here: https://github.com/google/ts-style/releases/edit/untagged-6f08f4d4687c3a8fc5a9
=> chore(package): bump to v0.7.0

package-lock.json, package.json
release notes: https://github.com/google/ts-style/releases/edit/untagged-02540ef39887e0b776b6
=> chore(package): bump to v0.7.1

src/init.ts, src/lint.ts, test/test-lint.ts
Depends-upon: https://github.com/palantir/tslint/pull/4143
Fixes: https://github.com/google/ts-style/issues/172
This should not be landed until https://github.com/palantir/tslint/pull/4143 gets into a tslint release.
=> fix(lint): skip lint on json files

test/test-kitchen.ts
=> fix: address post-landing comments

.circleci/config.yml
NOTE: this targets the `next` branch.
=> build: stop testing on Node 6

src/format.ts
Fixes: https://github.com/google/ts-style/issues/270
=> fix: provide filepath to prettier

README.md
Fixes: https://github.com/google/gts/issues/279
Fixes: https://github.com/google/gts/issues/277
=> doc: warn about master, released version delta

package-lock.json, package.json
This is a release candidate working towards a 1.0.
Release notes: ~~https://github.com/google/ts-style/releases/edit/untagged-3b44a43c9e5809bfe52e~~
https://github.com/google/ts-style/releases/edit/untagged-840222fc22192853a87b
=> Release 1.0.0-0

.clang-format
=> cleanup: remove unnecessary .clang-format

package-lock.json, package.json, test/fixtures.ts, test/mocha.opts, test/test-clean.ts, test/test-format.ts, test/test-init.ts, test/test-kitchen.ts, test/test-lint.ts, test/test-util.ts
Fixes #260.  @ofrobots I did most of the grunt work here, and now I'm just fighting a few failing tests.  I pushed this to upstream so we could maybe collaborate on this one.   
Side note: really suggest enabling 'hide whitespace changes' for this one
=> refactor(test): convert tests to mocha

package-lock.json
after manual conflict resolution in different pr
=> chore: updating package-lock.json

package-lock.json, package.json
This will help #333 go down smoother believe it or not
=> build: use c8 for code coverage

test/mocha.opts, test/test-kitchen.ts
The special behavior for windows and npx wasn't needed, and things just run a little slower here :)  These seem to pass running on my windows VM.  Eager to see what happens over in #332!
=> test: get windows tests passing

.ci/docker/windows/Dockerfile, .cirrus.yml
I saw #331 and decided to take a look. 
@JustinBeckwith @ofrobots PTAL
=> build: Configure Cirrus CI for Windows

.cirrus.yml
=> build: use correct task names in the CI config

package-lock.json, package.json, src/util.ts
=> chore(deps): upgrade typescript to ~3.5.0

package-lock.json, package.json
updates us to the newest prettier, which now supports optional chain.
=> fix(deps): update to newest prettier (with support for optional chain)

.eslintrc.json
=> feat!: add the eol-last rule

README.md
=> docs: add eslint details

src/cli.ts
=> fix: include *.tsx and *.jsx in default fix command

.eslintrc.json, src/cli.ts
closes https://github.com/google/gts/issues/546
=> feat: no floating promises

package-lock.json, package.json
=> chore(deps): bump typescript version

.github/workflows/ci.yaml, .github/workflows/release.yaml, package-lock.json, package.json, test/kitchen.ts
Drop Support for older versions of Node.js
=> feat!: Support Node 18+

tsconfig-google.json
=> feat!: Set `stripInternal` in `tsconfig-google.json`

tsconfig-google.json, tsconfig.json
=> feat!: Set `composite: true` in `tsconfig-google.json`

.eslintrc.json, src/cli.ts
=> feat!: Set `no-floating-promises` to `error`

package-lock.json, package.json, src/init.ts, test/test-init.ts
=> feat!: Update `typescript` and other dependencies
