- src/cli.ts
- src/init.ts
- src/lint.ts
The paths we generate in scripts and config should be from the local
node_modules folder rather than pointing to the global directory (may
not persistent as node version changes) or npx directory (may not exist
across invocations).
Also did some refactoring.
Going to start writing tests pretty soon.
> fix: use local path to module

- src/cli.ts
- src/fix.ts
- src/lint.ts
https://palantir.github.io/tslint/usage/library/
> lint: start using tslint library api

- package-lock.json
- package.json
- src/cli.ts
- src/fix.ts
- src/init.ts
- src/lint.ts
- test/fixtures.ts
- test/fixtures/kitchen/tsconfig.json
- test/test-lint.ts
- test/test-util.ts
- tsconfig-google.json
Makes it possible to run runs with fixtures without having out of band
fixtures directories.
Add tests for lint.ts.
> test: add fixture mechanism for unit testing

- tsconfig-google.json
The internal Google configuration doesn't use this flag.
Fixes: https://github.com/google/ts-style/issues/39
> drop noUnusedParameters

- package.json
- src/cli.ts
> fix: conditionally require lint, format

- package.json
- src/init.ts
- src/util.ts
`read-package-json` [inserts a number of fields](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/554/files/6e59f889f953868ebe198969be7908400af202f1..e875441c58e0de2cfd0e1784605cfcf0d6986311#r139029874) that we likely don't want to write to the user's `package.json` file. This change replaces it with `readFilep` followed by `JSON.parse`.
We might lose some guarantee about the structure of the `package.json` file being read (seems like `read-package-json` does some extra checks)... but these cases might be unrecoverable either way.
> Replace read-package-json with vanilla JSON.parse

- package-lock.json
- package.json
TypeScript doesn't follow semver. The 2.6 release today is breaking our
CI. This change locks it down to a safer semver range.
> chore: restrict typescript version

- src/init.ts
- test/test-kitchen.ts
Fixes: https://github.com/google/ts-style/issues/68
> fix: add terminal newline to tsconfig.json

- src/lint.ts
- test/test-lint.ts
This is needed when files are explicitly passed to
gts. Just ignore them.
This addresses https://github.com/google/ts-style/issues/86
> fix: ignore files that are not found

- README.md
This repo is making the rounds on twitter today and in the Angular community, and they are confused because we've been committed to TSLint and clang-format in the past. They got the impression this repo is a new implementation of these tools.
> docs: Clarify that this isn't a formatter/linter

- src/cli.ts
- test/test-kitchen.ts
Fixes: https://github.com/google/ts-style/issues/83
Done ~~We need tests for use as a global install module.~~
Done #89 ~~It is worth noting that we do not expect `gts compile` to work from a globally installed version. We need to detect that case and show an error to the user in that scenario.~~
> fix: correct gts root directory

- src/format.ts
- test/fixtures/kitchen/src/server.ts
- test/test-format.ts
Fixes #98
We should use `getRootFileNames` instead of `getSourceFiles` when retrieving a list of files to format; the latter gets every files in the dependency graph constructed from files included in `tsconfig.json`.
> fix: format root files only

- src/init.ts
TypeScript doesn't follow semver, but we do. It makes sense to default
to a ~ semver range for typescript in the client projects, rather them
letting them stumble into the subtlety.
> fix(init): use ~ semver range for typescript

- package-lock.json
- package.json
Supersedes #97
The `clang-format` module incorporates changes to formatting rules as semver patch-level changes. This is undesirable for users of our module, as we treat changes in formatting as semver-major. This PR addresses this by pinning `clang-format` to 1.2.1; going forward we should increment the pinned version with each semver-major bump of this module.
> chore: upgrade and pin clang-format at 1.2.1

- package-lock.json
- package.json
Run `jsgl` on the repository as one of posttest checks.
> chore: add license checking with js-green-license

- package-lock.json
- test/test-kitchen.ts
`gts init` must be done before `gts check`.
Not sure how this has been passing so far. This started to fail
suddenly.
> fix: fix a failing test

- src/init.ts
- test/test-kitchen.ts
Currently the global gts path is used when `gts init` is done using a
globally installed `gts`, which is a usual workflow.
> fix: use local gts path for generated tsconfig.json

- package-lock.json
- package.json
- src/cli.ts
- src/init.ts
- src/util.ts
- test/fixtures.ts
- test/test-kitchen.ts
- tsconfig-google.json
[BREAKING CHANGE]
This PR is both for the generated `package.json` and `gts` itself.
TypeScript 2.7.1 added `--esModuleInterop` for better ES module
support. And for that, we need to turn on `allowSyntheticDefaultImports`
too.
Also `tslint` must be upgraded to 5.9.1 for it to compile with
`esModuleInterop`.
> feat: use typescript 2.7.1 and esModuleInterop

- package-lock.json
- src/init.ts
- test/test-kitchen.ts
Compilation would fail because there's no source files.
> fix: don't compile right after generating a project

- package-lock.json
- package.json
- src/init.ts
This is for the next branch.
Update the typescript dependency to 2.8.x both for the locally used dev
dependency and the version we emit in the generated package.json. The
peerDependency remains unchanged, which makes this a semver-minor.
Existing projects already have a dependency on typescript in their
package.json, so they should continue using the pre-2.8 version.
New versions projects will get 2.8.1+.
> feat: upgrade to Typescript 2.8.x

- src/init.ts
tsconfig.json doesn't need an exclude section when an include section
is present.
Fixes: https://github.com/google/ts-style/issues/70
> fix: exclude section is not necessary

- .circleci/config.yml
- package.json
BREAKING CHANGE. Stop supporting Node 4.x.
> chore: drop support for Node 4

- tsconfig-google.json
BREAKING CHANGE: since we no longer support Node 4.x, we can default
to the target ES2016.
Fixes: https://github.com/google/ts-style/issues/147
> feat: change default target to es2016

- README.md
This module has had enough exposure that it is no longer experimental.
> chore: drop 'experimental' from README

- test/test-clean.ts
- test/test-format.ts
- test/test-lint.ts
This ensures that the tests are independent of where they are run from.
Remove a test that was unnecessary.
> test: resolve gtsRootDir in tests

- README.md
- src/lint.ts
- test/test-lint.ts
This change adds the ability to use tslint.conf provided by the user.
If the user doesn't have a config file, we fall back to the default
gts config file.
This depends on #158, so ignore that commit when reviewing. That commit will be removed once #158 lands.
We do prefer the user-provided config file over the default now, which is potentially breaking, but I doubt users ever had the reason to have a local `tslint.json` before. I don't think this is semver major, but feel free to push back.
> feat: ability to use user provided tslint config

- README.md
- src/init.ts
- test/test-kitchen.ts
`init` now generates a tslint.json file which inherits from the default
configuration. This empowers the users to customize if necessary
instead of being overly opinionated.
Fixes: #127
Fixes: #119 
This depends upon #158 and #159, so the first two commits don't need to be reviewed. They will be removed once those PRs land.
> feat: generate tslint.json

- src/format.ts
- src/init.ts
- test/test-kitchen.ts
`init` now generates a .clang-format file. This allows IDEs to pick up
the config and integrate well with the gts provided style.
Fixes: https://github.com/google/ts-style/issues/120
> feat: generate .clang-format

- src/lint.ts
- test/test-lint.ts
When invoked with a list of files, linter configuration pertaining to
those files should be preferred rather than the gts default config.
> fix: use correct lint config for individual files

- src/lint.ts
- test/test-lint.ts
Fixes: https://github.com/google/ts-style/issues/118
> fix: fix with --dry-run should not modify files

- test/test-clean.ts
- test/test-format.ts
- test/test-lint.ts
> test: minor cleanup

- src/format.ts
- test/test-format.ts
> fix: do not fix format errors with --dry-run

- src/format.ts
- test/test-format.ts
This fixes a regression in v0.7.0.
> fix(format): deal with absent .clang-format

- src/init.ts
Fixes: https://github.com/google/ts-style/issues/144
> fix(init): init package with better main, types

- package-lock.json
- src/format.ts
- src/init.ts
- test/test-format.ts
- test/test-init.ts
In an effort to improve coverage, I started working some tests. It turns out that our current coverage numbers are a lie as `init.ts` wasn't accounted for. It only gets tested via `test-kitchen.ts` which is hard to report for coverage purposes (it uses an tarball-installed version of the package rather than the existing files).
Here some more tests. Still more to come, but no reason to sit on these. These can land.
> Add more tests

- src/cli.ts
- src/util.ts
- test/fixtures.ts
- test/test-format.ts
- test/test-init.ts
- test/test-kitchen.ts
- test/test-lint.ts
- tsconfig-google.json
BREAKING CHANGE: esModuleInterop causes synthetic imports to leak from
libraries to their users. Users must compile with allowSyntheticImports
as well if they use a library that uses this flag.
This has been causing a lot of churn in libraries that use gts.
> fix: disable esModuleInterop

- tsconfig-google.json
BREAKING CHANGE: Similar to #183, also disable synthetic imports.
> fix: also disable allowSyntheticDefaultImports

- package-lock.json
- package.json
[release notes](https://github.com/google/ts-style/releases/edit/untagged-8135d45fa5980f0bd20b)
---
This is a release with breaking changes. We no longer set the `esModuleInterop` and `allowSyntheticDefaultImports` in the default TypeScript config. These might be reasonable configurations for end-user application code, but for libraries these can be problematic. TypeScript users of such libraries must have these flags set as well for compilation to succeed. For example: https://github.com/google/google-auth-library-nodejs/issues/381.
There are two ways to deal with this breaking change:
* (recommended) change code using synthetic imports (`import fs from 'fs'`) back to using old style imports (`import * as fs from 'fs'`).
* Add `"esModuleInterop": true` to your local `tsconfig.json`. …
> chore(release): bump version for 0.8.0

- src/clean.ts
- src/util.ts
- test/test-util.ts
I wrote and edited the tests to show the new functionality and to catch circular references. This still should be abstracted to effect all commands that look at the contents of tsconfig.json. Also there is no support for compileOnSave yet. fix: #64
> fix: allow 'gts clean' to follow tsconfig.json dependency chain

- src/init.ts
- test/test-init.ts
- test/test-lint.ts
In code:
- Changed "DEF**UA**LT_PACKAGE_JSON" to "DEF**AU**LT_PACKAGE_JSON" (usages also updated)
In comments:
- Changed "def**ua**lt" to "def**au**lt"
- Changed "sensi**s**tive" to "sensitive"
- Changed "in**lc**ude" to "in**cl**ude"
> Fixed typos

- renovate.json
Removed `"gitAuthor": null` from `renovate.json` file, because renovate requires [RFC5322-compliant string](https://github.com/renovatebot/renovate/blob/master/website/docs/self-hosted-configuration.md#gitauthor) and `null` is not a string. Furthermore, the default value for `gitAuthor` is `null` according to [docs](https://renovatebot.com/docs/self-hosted-configuration/#gitauthor).
This file was added in e107ab3e9180a69c74aafe7eb683a0f6d70bd7dc commit and was never changed after that.
> Removed gitAuthor from renovate.json

- tslint.json
Our eslint config checks to make sure we don't use deprecated APIs, and throws in that case.  Our tslint config does not.  This bit us in real life, where an `assert.equal` was allowed to get checked in, and it didn't properly check strictness.
> fix: do not allow deprecated methods

- .prettierrc
- README.md
- package-lock.json
- package.json
- prettier.config.js
- src/clean.ts
- src/cli.ts
- src/format.ts
- src/init.ts
- src/lint.ts
- src/util.ts
- test/fixtures.ts
- test/test-clean.ts
- test/test-format.ts
- test/test-init.ts
- test/test-kitchen.ts
- test/test-lint.ts
- test/test-util.ts
NOTE: this targets the next branch.
BREAKING CHANGE: Switch to prettier as the code formatter.
> feat!: switch to prettier for formatting

- src/cli.ts
- src/init.ts
- src/util.ts
- test/test-init.ts
- test/test-util.ts
> Support Yarn

- package-lock.json
- package.json
- src/init.ts
- test/test-init.ts
- Removes manual `package.json` types.
- Uses `@types/package-json` instead.
Note: Import order sorted automatically via VSCode.
> fix: Remove manual package.json interface

- test/fixtures.ts
- test/mocha.opts
- test/test-clean.ts
- test/test-format.ts
- test/test-kitchen.ts
- test/test-util.ts
The first PR in a series. Here's a PR which makes tests pass.
The next should be:
> Make tests pass after migration to Mocha

- tslint.json
While not part of the internal style guide (yet), enforcing trailing
commas make sense as they make diffs simpler. They would would give us
better congruence with the JS style guide.
Fixes: https://github.com/google/gts/issues/292
> fix!: lint enforce trailing commas

- .circleci/config.yml
CI should use npm-ci to install https://docs.npmjs.com/cli/ci.html. It
is faster cleaner and stricter and doesn't update package-lock as part
of the install.
> build: use npm ci in the ci

- package.json
It's redundant after #299 (make-dir will be installed as a dependency of `inline-fixture`)
> chore: remove redundant dependency (mkdir)

- package-lock.json
- package.json
- src/init.ts
- test/test-init.ts
We get 'official' types from the horse's mouth now. Let's use those.
Oh, and `package-json` stopped exporting the types for package.json
itself. Let's not use that anymore.
> deps: switch to @npm/types for package.json types

- src/lint.ts
tslint seems to have a memory leak such that, in codebases with a lot of files like `google-api-nodejs-client`, we're bumping into OOM issues, here's an example: 
https://github.com/googleapis/google-api-nodejs-client/pull/1778
The problem crops up when `getResult` is called on a large set of files.
It doesn't seem like, for the purposes of linting, there should be any state shared between the files added to the linter, this PR proposes linting a maximum of 25 files in conjunction, and then creating a new `Linter` instance.
I've confirmed that this fixes our issues with `google-api-nodejs-client`.
> fix: process less files in parallel preventing OOM errors

- .github/release-please.yml
I'd like to cut a new release for TypeScript 3.7 support, but I just can't be bothered to follow the old process anymore.  @bcoe has ruined me.
> build: use release-please

- .cirrus.yml
- package-lock.json
- package.json
- tsconfig-google.json
BREAKING CHANGE: This commit drops support for node.js 8.x.  Additionally, the base tsconfig has been upgraded to target the es2018 feature set, which is fully supported by node.js 10.x.
> fix!: drop support for node 8

- package.json
- src/init.ts
- test/test-init.ts
Since TypeScript [v1.5.0-alpha](https://github.com/microsoft/TypeScript/blob/b18dd53242df31163390c411ac7ab5e9c282fea2/src/compiler/tsc.ts#L185) `tsc` will search for `tsconfig.json` in `cwd` by default.
First implemented in https://github.com/microsoft/TypeScript/pull/1692.
So, there's no need in specifying project path anymore and we can safely replace `tsc -p .` with just `tsc`.
> refactor: compile using tsc with no arguments

- package-lock.json
- src/init.ts
- test/kitchen.ts
`npx gts init` was previously emitting a `.prettierrc.json` that hard coded the config we use locally.  Instead, emit a `.prettierrc.js` that can extend the config.
> fix: emit .prettierrc.js with init

- .eslintrc.json
- package.json
require-atomic-updates is a bit too strict, and is currently being tracked as a bug
here: https://github.com/eslint/eslint/issues/11899
> feat: override require-atomic-updates

- .eslintrc.json
The current eslintrc ignores tsx files.
> feat: allow eslintrc to run over tsx files

- .prettierrc.json
Put it back. Will be released as `2.0.0-alpha.8` and tagged `next`.
> fix: enable trailing comma

- template/index.ts
Template can't be compiled because of `TS7030`.
```
error TS7030: Not all code paths return a value.
```
Fixed by adding dummy return.
> docs: example template compile fix

- .eslintrc.json
- src/clean.ts
- src/init.ts
- test/test-init.ts
Warn if single quotes are not used in a situation in which this is possible. see: https://eslint.org/docs/rules/quotes
This rule lets us catch the [behavior discussed here](https://github.com/googleapis/google-cloud-node/issues/2915), in which a template string is used with no replacements.
I've opted for a warning rather than an error, as in testing it seemed like this rule could be a bit disruptive for folks who write strings like this:
```
"hello 'world'"
```
as it requires the replacement:
```
'hello "world"'
```
fixes: https://github.com/googleapis/google-cloud-node/issues/2915
> feat!: prefer single quotes if possible, raising warning

- README.md
- src/cli.ts
- test/test-clean.ts
> fix: throw an error if running with an unsupported version of nodejs

- package-lock.json
- package.json
This reverts commit 6aee1595d0486ae2c7fd68d16b1b59c4c4015753.  I shouldn't have merged this commit, since it would have likely introduced breaking changes for downstream clients.
> fix: Revert 'update dependency eslint to v7'"

- src/init.ts
- test/kitchen.ts
- generate `.eslintignore` and include `build/`
- add empty line at enf of generated `.prettierrc.js`
solves https://github.com/google/gts/issues/483
solves https://github.com/google/gts/issues/520
> feat: generate .eslintignore when running init

- .eslintrc.json
Prevent calls to ".only" in mocha tests. Porting upstream from nodeJS-firestore (original [PR](https://github.com/googleapis/nodejs-firestore/pull/1068)).
> fix: prohibit calls to `it.only` and `describe.only`

- src/util.ts
If `tsconfig.json` cannot be parsed (invalid JSON) we should not say that it's not found.
> fix: better error message for broken tsconfig.json

- package.json
There is `.eslintrc.json` in `build/` directory that is generated by tsc. This file is loaded from `build/src/index.js` but not listed in the files field.
This is already included in published tarballs. 
```
$ curl -s https://registry.npmjs.org/gts/-/gts-2.0.2.tgz | tar tv | grep .eslintrc.json
-rw-rw-r--  0 0      0        1407 10 26  1985 package/.eslintrc.json
-rw-rw-r--  0 0      0        1663 10 26  1985 package/build/.eslintrc.json
```
This pr not only makes this package correct.
To add this file makes us able to use the head version from the GitHub repository, using `yarn add -D gts@git+https://github.com/google/gts.git#master`.
In installing from [git dependency](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), the `prepare` script runs and compiles typescript …
> fix: Add build/.eslintrc.json to the files field in package.json

- .eslintrc.json
It's a common pattern to `require('package.json')` to determine the version # of an application.
We do this in all of our auto generated code:
https://github.com/googleapis/nodejs-asset/pull/403/files
If we switch these `require` statements to `import` statements, it breaks publication of our libraries, because TypeScript copies the `package.json` into the `build/` folder, which in turn stops npm from publishing assets in that folder.
`require` isn't just used for pulling in JavaScript files, it's convenient for loading JSON fixtures other than `package.json`, .e.g., `test/fixtures/foo.json` -- this is a useful pattern in tests which we'd now need to add ignore rules for.
> fix(rule): turn off @typescript-eslint/no-var-requires

- src/init.ts
- test/kitchen.ts
resolve https://github.com/google/gts/issues/445
I agree that having `.editorconfig` would be nice. Not sure how the config should look like for this project though.
> feat: generate .editorconfig

- package-lock.json
- package.json
- src/cli.ts
Fixes #704 by just removing the `update-notifier` dependency all together.  This was largely used to give users a message using `gts` from the CLI that they need to upgrade.  Realistically, we expect most users to be using `npx`, or to have `gts` installed in the `package.json` and to use it from `npm run` scripts.  
This is a no-win situation because:
- `update-notifier` has a security vuln in the previous major version
- The new version is ESM only
- ESLint plugins don't work with ESM
I don't think this dependency was worth it.
> fix: drop update notifier

- .eslintrc.json
- src/cli.ts
This reverts commit c93e73316164137e29daa7bea8a48083f7d7c1da.
This `project` property is breaking `lint` in the following libraries:
- https://github.com/googleapis/nodejs-googleapis-common
- https://github.com/googleapis/google-auth-library-nodejs
- https://github.com/googleapis/gaxios
- https://github.com/googleapis/nodejs-pubsub
Error message:
```
Parsing error: ESLint was configured to run on `<tsconfigRootDir>....` using `parserOptions.project`: .../tsconfig.json
However, that TSConfig does not include this file.
```
We should include this in the next major instead as the requires a coordinated release.
> Revert "feat: no-floating-promises (#756)"

- .pre-commit-hooks.yaml
- README.md
> feat: adding pre-commit-hooks.yaml

- README.md
Fixes for broken Dependency Status badge image.
For reference: https://github.com/alanshaw/david/issues/182
> docs: removes broken dependency status and markdown format

- .prettierrc.json
- package.json
- src/clean.ts
- src/cli.ts
- src/init.ts
- src/util.ts
- test/kitchen.ts
- test/test-clean.ts
- test/test-init.ts
- test/test-util.ts
> feat!: Update '.prettierrc.json' to include `trailingComma: "all"` to match internal Google config

- package.json
This isn't breaking as it is improving backwards compatibilty.
> fix: Allow `typescript` v5+ as a peer dependency

- tsconfig-google.json
Should be at least 2022 for `target`, 2023 for `lib`.
Background: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
> fix: TS `lib` Support for Node 18+
